// Проба решений после встречи с ментором 06.10 (mentor1006.py): node mentor_probe.mjs <путь к html>
import { createRequire } from 'module';
import { pathToFileURL } from 'url';
const require = createRequire(process.cwd() + '/package.json');
const { chromium } = require('playwright');
const f = pathToFileURL(process.argv[2]).href;
const b = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const errs = [], res = [];
const ok = (n, c, d) => res.push((c ? 'PASS ' : 'FAIL ') + n + (c ? '' : ' :: ' + d));
const fresh = async () => { const p = await b.newPage({ viewport: { width: 375, height: 812 } }); p.on('pageerror', e => errs.push(e.message)); await p.goto(f + '?clean&s=fresh'); await p.waitForTimeout(300);
  await p.evaluate(() => { me().consent = true; S.draft = null; go('phrase'); render(); $('#phrase').value = 'Ноутбук 90 тысяч к 1 марта, плачу сам'; ACT.phraseGo(); }); return p; };
let p = await fresh();
let r = await p.evaluate(() => { const n0 = S.purchases.length; ACT.v3save(); const sheet = S.sheet, txt = $('#sheet').innerText; ACT.mSkip(); return { sheet, txt, saved: S.purchases.length > n0, scr: S.scr, auth: me().auth || null }; });
ok('«Сохранить цель» без входа: лист входа, «Сохранить без входа» сохраняет цель', r.sheet === 'login' && r.saved && !r.auth && r.scr !== 'answer', JSON.stringify(r));
r = await p.evaluate(() => { S.draft = null; go('phrase'); render(); $('#phrase').value = 'Диван 50 тысяч к 1 мая, плачу сам'; ACT.phraseGo(); const n0 = S.purchases.length; ACT.v3save(); return { sheet: S.sheet, saved: S.purchases.length > n0 }; });
ok('после отказа вторая цель сохраняется без повторного листа', r.saved && r.sheet !== 'login', JSON.stringify(r));
await p.close();
p = await fresh();
r = await p.evaluate(() => { const n0 = S.purchases.length; ACT.v3save(); ACT.mLoginMail(); const s1 = S.sheet;
  $('#mmail').value = 'abc'; $('#mmailf').requestSubmit(); const e1 = (document.getElementById('mmail-err') || {}).textContent;
  $('#mmail').value = 'name@mail.ru'; $('#mmailf').requestSubmit(); const step = !!$('#mcode');
  $('#mcode').value = '12'; $('#mcodef').requestSubmit(); const e2 = (document.getElementById('mcode-err') || {}).textContent;
  $('#mcode').value = '123456'; $('#mcodef').requestSubmit(); return { s1, e1, step, e2, auth: me().auth, saved: S.purchases.length > n0 }; });
ok('код на почту: ошибка адреса и кода под полем, после кода — вход и цель сохранена', r.s1 === 'mMail' && /ошибка/.test(r.e1) && r.step && /6 цифр/.test(r.e2) && r.auth === 'mail' && r.saved, JSON.stringify(r));
r = await p.evaluate(() => { go('data'); return (document.querySelector('#view').innerText.match(/[^\n]*Вход:[^\n]*/) || [''])[0]; });
ok('«Мои данные»: «Вход: код на почту»', /код на почту/.test(r), r);
await p.close();
console.log(res.join('\n')); console.log('PASS', res.filter(x => x.startsWith('PASS')).length, '/', res.length, '· errors', errs.length, errs.slice(0, 3));
await b.close();
